### ISSUE TITLE
Quick post doesn't work

### ISSUE THREAD

**Issue by stormyqq** [PirataNervo/newpoints#9] opened 2017-02-02 23:19 UTC
It posts, but still not display the post without refreshing the page, but as soon as the plugin is disabled the quick post appears when it's posted without refreshing the page.

**Comment by stormyqq** [comment] 2017-02-03 01:32
https://github.com/PirataNervo/newpoints/compare/master...stormyqq:patch-1
It's fixed.

**Comment by PirataNervo** [comment] 2017-02-16 13:33
Thanks :)

**Comment by PirataNervo** [comment] 2017-03-17 13:01
Duplicate of #8 .

I can't accept your Pull Request because it modifies parts which are not required (only the preg_replace call which uses the e modified needs to be changed) and because your modification to the first call of preg_replace doesn't do what it's supposed to.

It's supposed to remove the quote tags, not to keep the quote tag that matches the first pattern, as your fix does. The code was originally part of http://forums.mybb-plugins.com/Thread-OUGC-Post-Character-Count-Enhancement but I failed to notice the e modified.

To my knowledge, simply removing it fixes the issue, because we don't need to evaluate any code within it. We just want to strip everything that matches the first pattern.

**Closed by PirataNervo** 2017-03-17 13:01 UTC
Labels: bug

**Comment by stormyqq** [comment] 2017-03-17 13:42
well actually your code wasn't compatible with php7, and I made it
compatible with it. anyway it's up to you accept or not, I don't really
care.

**Comment by PirataNervo** [comment] 2017-03-18 14:33
Yes, your code made it compatible but wouldn't work as expected. It would give no warnings but the code wouldn't remove the quote tags properly. I've fixed it by simply removing the 'e' modified, which is deprecated and we don't need to eval anything so we don't need to use the _callback function.

Anyway, thanks for putting your time into this.

**Comment by stormyqq** [comment] 2017-03-19 12:30
actually I removed the e modifier too with my edit, otherwise the php
wouldn't stop throwing the error.  _callback function is recommended with
the php7. I don't really care whatever you do with your tool, but I am
disappointed that my edit wasn't accepted, even though it's perfectly okay.
so I don't think I am gonna contribute to any of your project anymore, as
it's a waste of my time.

**Comment by PirataNervo** [comment] 2017-03-19 18:32
I think you're not understanding. The callback function may be recommended but your solution would replace the match with the content of $match[0] which doesn't make sense because we want to strip the quote tag and its contents. Basically, your PR doesn't fix the issue, it fixes the warning.
